name: emotiovent
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  responsive_flutter: ^0.0.4
  flutter:
    sdk: flutter
  
  provider: ^4.3.2+2

  shake: ^0.1.0
  sensors: ^0.4.2+6

  dart_random_choice: ^0.0.2
  
  # Check that you have this dependency (added in the previous step)
  firebase_core: ^0.5.2

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^6.2.0

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SegoeUIBlack
      fonts:
        - asset: assets/font/segoeui/seguibl.ttf
          style: normal
    - family: Aileron
      fonts:
        - asset: assets/font/aileron/Aileron-Regular.otf
          style: normal
        - asset: assets/font/aileron/Aileron-Italic.otf
          style: italic
        - asset: assets/font/aileron/Aileron-Bold.otf
          weight: 300
        - asset: assets/font/aileron/Aileron-Black.otf
          weight: 900
        - asset: assets/font/aileron/Aileron-BlackItalic.otf
          weight: 900
          style: italic
    - family: BalsamiqSans
      fonts:
        - asset: assets/font/balsamiq/BalsamiqSans-Regular.ttf
          style: normal
        - asset: assets/font/balsamiq/BalsamiqSans-Bold.ttf
          weight: 700
        - asset: assets/font/balsamiq/BalsamiqSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/balsamiq/BalsamiqSans-Italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/font/roboto/Roboto-Regular.ttf
          style: normal
        - asset: assets/font/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/font/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/roboto/Roboto-Light.ttf
          weight: 100
        - asset: assets/font/roboto/Roboto-LightItalic.ttf
          weight: 100
          style: italic
        - asset: assets/font/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/font/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Nexa
      fonts:
        - asset: assets/font/nexa/Nexa-Bold.otf
          weight: 700
        - asset: assets/font/nexa/Nexa-Light.otf
          weight: 100
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
